routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{GlassesController, GlassSearchController, CategorySearchController};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [GlassesController::class, 'index'])->name('index');
Route::get('/glass-search', [GlassSearchController::class, 'index'])->name('glass-search');
Route::get('/category/{category}', [GlassSearchController::class, 'category'])->name('category');
Route::get('/brand/{brand}', [GlassSearchController::class, 'brand'])->name('brand');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\{Model, SoftDeletes};

class Brand extends Model
{
    use HasFactory, SoftDeletes;
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\{Builder, Model, SoftDeletes};

class Category extends Model
{
    use HasFactory, SoftDeletes;

    public function glasses(): Builder{
        return $this->hasMany(Glass::class);
    }
}

app/Models/Glass.php
<?php

namespace App\Models;

use App\Filters\GlassFilter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\{Builder, Model, SoftDeletes};
use Illuminate\Http\Request;


class Glass extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images()
    {

        return $this->hasMany(Image::class);

    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function image()
    {
        return $this->hasOne(Image::class)
            ->where('order', '=', 0)
            ->where('active', '=', 1);
    }

    /**
     * @param int|null $value
     * @return float
     */
    public function getPriceAttribute(?int $value = 0): float
    {
        return number_format($value / 100, 2);
    }

    /**
     * @param Builder $builder
     * @param Request $request
     * @return Builder
     */
    public function scopeFilter(Builder $builder, Request $request)
    {
        return ($this->resolveFilter($request))->filter($builder);
    }

    /**
     * @param Builder $builder
     * @param Request $request
     * @return Builder
     */
    public function scopeRelationFilter(Builder $builder, Request $request)
    {
        return ($this->resolveFilter($request))->relationFilter($builder);
    }

    /**
     * @param Builder $builder
     * @param Request $request
     * @return Builder
     */
    public function scopeCommonFilter(Builder $builder, Request $request)
    {
        return ($this->resolveFilter($request))->multiFilter($builder);
    }

    /**
     * @param Request $request
     * @return GlassFilter
     */
    private function resolveFilter(Request $request){
        return new GlassFilter($request);
    }
}

app/Models/Image.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use App\Interfaces\ModelsRepository;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    protected $repository;

    /**
     * Controller constructor.
     * @param ModelsRepository $repository
     */
    public function __construct(ModelsRepository $repository)
    {
        $this->repository = $repository;
    }
}

app/Http/Controllers/GlassSearchController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategorySearchRequest;
use App\Http\Requests\GlassBrandRequest;
use App\Http\Requests\GlassCategoryRequest;
use App\Http\Requests\GlassSearchRequest;
use Illuminate\Http\Request;

class GlassSearchController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(GlassSearchRequest $request)
    {
        $glasses = $this->repository->commonFilter($request)->with('image')->paginate(config('view.paginate.glass-search'));
        $request->flash();
        return view('glasses.index', compact('glasses'));
    }

    /**
     * @param GlassCategoryRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function category(GlassCategoryRequest $request)
    {

        $glasses = $this->repository->relationFilter($request)->with('image')->paginate(config('view.paginate.glass-search'));
        $request->flash();
        return view('glasses.index', compact('glasses'));
    }

    /**
     * @param GlassBrandRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function brand(GlassBrandRequest $request)
    {
        $glasses = $this->repository->relationFilter($request)->with('image')->paginate(config('view.paginate.glass-search'));
        $request->flash();
        return view('glasses.index', compact('glasses'));
    }
}

app/Http/Controllers/GlassesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GlassRepositoryUpdateRequest;
use Illuminate\Http\Request;

class GlassesController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $glasses = $this->repository->paginateModels();
        return view('glasses.index', compact('glasses')) ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param GlassRepositoryUpdateRequest $request
     * @param $id
     */
    public function update(GlassRepositoryUpdateRequest $request, $id)
    {
        $this->repository->updateModel($id, $request->validated());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/glasses/card.blade.php
<div class="card m-2" style="width: 20rem;">
    <img class="card-img-top" src="{{$glass->image->src}}" alt="Card image cap">
    <div class="card-body d-flex align-items-start flex-column bd-highlight">
        <div class=" bd-highlight"><h5 class="card-title"><strong>{{ucwords($glass->name)}}</strong></h5></div>
        <div class=" bd-highlight"><h6 class="card-title">category: {{$glass->category_id}} &nbsp brand: {{$glass->brand_id}}</h6></div>
        <div class=" bd-highlight"><h6 class="card-title"></h6></div>
        <div class="mb-auto bd-highlight"><p class="card-text"><em>{{\Illuminate\Support\Str::limit($glass->description, 50)}}</em></p></div>
        <div class="d-flex w-100 mt-3">
            <a href="#" class="btn btn-primary pl-4 pr-4">Buy</a>
            <h3 class="ml-auto mb-0 pt-1">${{$glass->price}}</h3>
        </div>
    </div>
</div>

resources/views/glasses/index.blade.php
@extends('layouts.app')
@section('content')
    <h1>The main content</h1>
    <div class="d-flex flex-wrap">
        @foreach($glasses as $glass)
            @if($glass->image()->exists())
                @include('glasses.card')
            @endif
        @endforeach
    </div>
    <div class="d-flex m-5">
        <div class="mx-auto">
            {{$glasses->appends(request()->input())->links()}}
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html>
<head>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
@include('layouts.header')

<div class="d-flex align-self-stretch"  style="background: content-box radial-gradient(yellow, skyblue);">
    <div class="bd-highlight col-2">
        @include('layouts.sidebar')
    </div>
    <div class="col-10 p-5">
        @include('layouts.errors')
        @yield('content')
    </div>
</div>
@include('layouts.footer')
</body>
</html>

resources/views/layouts/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/footer.blade.php
<div class="" style="background: content-box radial-gradient(yellow, skyblue);">
    <nav class="navbar navbar-expand-lg " >

        <a class="navbar-brand" href="#">
            <img  src="{{asset('images/pngwing2.com.png')}}" width="50" height="50" alt="" class="float-left mr-3">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

resources/views/layouts/header.blade.php
<div class="" style="background: content-box radial-gradient(yellow, skyblue);">
<div class="container-fluid ">
    <nav class="navbar navbar-light" >
        <a class="navbar-brand "  href="{{\Illuminate\Support\Facades\URL::to('/')}}">
            <img  src="{{asset('images/pngwing.com.png')}}" width="50" height="50" alt="" class="float-left mr-3">
            <h1>My Glasses</h1>
        </a>
        <ul class="nav justify-content-end p-3">
            <li class="nav-item">
                <a class="nav-link  active" href="#"><h5>Active</h5></a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#"><h5>Link</h5></a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#"><h5>Link</h5></a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><h5>Disabled</h5></a>
            </li>
        </ul>

        <form class="form-inline" action="{{route('glass-search')}}" method="get">
            <input value="{{old('common')}}" required name="common" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

    </nav>
</div>
</div>

resources/views/layouts/sidebar.blade.php
<nav class="nav flex-column pl-3">
    <h4 class="text-center">Categories</h4>
    <div class="side-bar-wrap mb-3">
        @foreach($categories as $category)
            <a style="background: content-box radial-gradient(yellow, skyblue);" class="nav-link mt-3 mb-1"
               href="{{route('category',['category' => $category->name])}}"><h5
                    class="text-center mb-0">{{ucwords($category->name)}}</h5></a>
        @endforeach
    </div>

    <h4 class="text-center">Brands</h4>
    <div class="side-bar-wrap mb-3">
        @foreach($brands as $brand)
            <a style="background: content-box radial-gradient(yellow, skyblue);" class="nav-link mt-3 mb-1"
               href="{{route('brand',['brand' => $brand->slug])}}"><h5
                    class="text-center mb-0">{{ucwords($brand->name)}}</h5></a>
        @endforeach
    </div>

</nav>